name: SamoTetris
options:
  bundleIdPrefix: com.samotetris
  deploymentTarget:
    iOS: 15.0
targets:
  SamoTetris:
    type: application
    platform: iOS
    deploymentTarget: 15.0
    sources:
      - ModernTetris
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.samotetris.app
      INFOPLIST_FILE: Info.plist
      TARGETED_DEVICE_FAMILY: 1
      SWIFT_VERSION: 5.9
